version: '3.3'

services:
  system-collector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    volumes:
      - logs:/app/logs
      - ./bin/configs/config.yaml:/app/configs/config.yaml
    networks:
      - system-network
    # 호스트의 서비스에 접근하기 위한 설정
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # 호스트에서 실행 중인 서비스 연결 정보
      - POSTGRES_HOST=host.docker.internal
      - INFLUXDB_URL=http://host.docker.internal:8086
    restart: unless-stopped

networks:
  system-network:
    driver: bridge

volumes:
  logs:
